version: '3.4'
services:
  api:
    build: ./api
    volumes:
      - ./api:/api
    environment:
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports: 
      - 8000:8000
    depends_on:
      - db
  
  app:
    build: ./app
    volumes:
      - ./app:/app
    environment:
      APP_MODE: ${APP_MODE}
      REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
    ports:
      - 3000:3000
    depends_on:
      - api
  
  db:
    image: mysql:8
    environment:
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql
  
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  mysql:
